on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    uses: exponentialcherub/deploy-pi/.github/workflows/deploy-pi.yml@v1.0.5
    with:
      app-name: "simple-messaging-queue"
      startup-cmd: "'PATH=$PATH:/usr/local/go/bin; go run queue.go'"
      branch: "main"
    secrets: inherit
